algoritmo "Apresentar Numeros"
// Função : Apresentar valores
// Autor : José Vitor
// Data : 01/09/2020
// Seção de Declarações 
var

ini, fim, i: inteiro

inicio
// Seção de Comandos 

escreva("Informe o número inicial: ")

leia(ini)

escreval ("")

escreva("Informe o número final: ")

leia(fim)

escreval ("")

para i de ini ate fim faca

escreval(i)

fimpara

fimalgoritmo
