algoritmo "Tabuada"
// Função : Tabuada
// Autor : José Vitor
// Data : 01/09/2020
// Seção de Declarações 
var

x,numero:inteiro

inicio
// Seção de Comandos 
escreval ("============ Tabuada by José ============")

escreval ("")

escreva ("Digite um numero: ")

leia(numero)

escreval ("")

escreval ("============ Tabuada do",numero," ============")

escreval ("")

para x de 1 ate 10 faca

escreval(numero," x ",x," = ",(numero * x))

fimpara
fimalgoritmo
